### ISSUE TITLE
Issue with team builder

### ISSUE THREAD

**Issue by Hebo360** [tyejae/msf.gg.public#96] opened 2019-09-21 19:27 UTC
I've recently finished adding my roster details (level, gear and power) and then attempted to setup my teams to show off these features to my alliance. however i can only select 38 random characters
![2019-09-21 (11)](https://user-images.githubusercontent.com/55636322/65378297-4285dc80-dcae-11e9-80c9-dd0e330729be.png)

**Comment by tyejae** [comment] 2019-11-26 19:47
Sorry for the late reply @Hebo360. Are you still seeing this issue? I cannot reproduce.

**Comment by Hebo360** [comment] 2019-11-26 20:30
Hi,

Thanks for getting back in touch. I'm not sure if it was an issue with the team builder or if I was doing something wrong but it seems to be working now.

Thank you for all the hard work you guys put into building/maintaining the website.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by tyejae** [comment] 2019-11-26 20:34
That's good news! I'll close this issue out then. Thanks.

**Closed by tyejae** 2019-11-26 20:34 UTC
