### ISSUE TITLE
Add Shard Count To Character History

### ISSUE THREAD

**Issue by tyejae** [tyejae/msf.gg.public#338] opened 2021-03-18 22:59 UTC
pager44 — Today at 1:17 PM
low priority request - any chance of getting shard count added to history? was just trying to look at the history of a char to see how quickly I'm farming them and predict how long to get to next star level

**Comment by jetroh** [comment] 2022-03-23 08:22
Duplicate of #215

**Closed by jetroh** 2022-03-23 08:22 UTC
